version: '3.8'

services:

  bank-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-service
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${SPRING_DATASOURCE_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ENC_SECRET: ${JWT_ENC_SECRET}

      CARD_ENC_SECRET: ${CARD_ENC_SECRET}

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/migration/master.yml
    ports:
      - "8080:8080"
    networks: [ bank_app ]
  db:
    image: postgres:15
    container_name: bank-postgres
    restart: always
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [ bank_app ]

networks:
  bank_app:
    driver: bridge

volumes:
  pgdata:
